# tensor normal operators

In [1]:
import tensorflow as tf

In [2]:
x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

## shape && size()

In [3]:
x.shape

TensorShape([12])

In [4]:
# No x.size()

## Number of elements tf.size(x)

In [5]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

## reshape

In [6]:
X = tf.reshape(x, (3, 4))
X
tf.size(X)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

## zeros

In [7]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

## ones

In [8]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

## random matrix 均值为0、标准差为1的标准高斯分布（正态分布）中随机采样

In [9]:
tf.random.set_seed(0)

In [10]:
tf.random.normal(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.5110626 ,  0.42292204, -0.41969493, -1.0360372 ],
       [-1.2368279 ,  0.47027302, -0.01397489,  1.1888583 ],
       [ 0.60253334,  0.5997111 , -0.7057119 , -0.43297544]],
      dtype=float32)>

In [11]:
tf.Variable(tf.random.normal(mean=1, shape=(3, 4)))

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 2.0668802 ,  1.1945493 ,  0.46917105,  1.0919008 ],
       [ 0.8224629 ,  0.08069116, -1.0777557 ,  3.0391903 ],
       [ 1.8028996 ,  0.06909633,  0.6275688 ,  0.6790262 ]],
      dtype=float32)>

我们还可以[**通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值**]。
在这里，最外层的列表对应于轴0，内层的列表对应于轴1。


## tf.constant(array)

In [12]:
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

## tf.constant(numpy)

In [13]:
import numpy as np
np_array = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tf.constant(np_array)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

## tf.convert_to_tensor(numpy)

In [14]:
np_array = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tf.convert_to_tensor(np_array)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

## tensor Operator
### + - * / ** are element-wise operator 

In [15]:
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x + y, 
x - y, 
x * y, 
x / y, 
x ** y  # **运算符是求幂运算

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>

(**“按元素”方式可以应用更多的计算**)，包括像求幂这样的一元运算符。


In [16]:
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
      dtype=float32)>

## concatenate: tf.concat()

In [17]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [18]:
tf.concat((X, Y), axis=0)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 2.,  1.,  4.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 4.,  3.,  2.,  1.]], dtype=float32)>

In [19]:
tf.concat((X, Y), axis=1)

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
       [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
       [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>

## homogenous

In [20]:
A = tf.concat((X, Y), axis=1)
rows = A.shape[0]
ones = tf.ones( (rows , 1 ))
tf.concat((A, ones), axis=1)

<tf.Tensor: shape=(3, 9), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.,  1.],
       [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.,  1.],
       [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.,  1.]], dtype=float32)>

## == operator, element-wise

In [21]:
X == Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

## True False to float in tensor

In [22]:
dropout = 0.5
mask = tf.random.uniform(shape=tf.shape(X), minval=0, maxval=1) < 1 - dropout
tf.cast(mask, dtype=tf.float32) * X / (1.0 - dropout)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  0.,  4.,  0.],
       [ 8., 10.,  0., 14.],
       [ 0.,  0., 20.,  0.]], dtype=float32)>

## Sum :  tf.reduce_sum(X) the sum of every number

In [23]:
tf.reduce_sum(X)
tf.Variable(tf.reduce_sum(X))

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=66.0>

## broadcasting

在上面的部分中，我们看到了如何在相同形状的两个张量上执行按元素操作。
在某些情况下，[**即使形状不同，我们仍然可以通过调用
*广播机制*（broadcasting mechanism）来执行按元素操作**]。
这种机制的工作方式如下：首先，通过适当复制元素来扩展一个或两个数组，
以便在转换之后，两个张量具有相同的形状。
其次，对生成的数组执行按元素操作。

在大多数情况下，我们将沿着数组中长度为1的轴进行广播，如下例子：


In [24]:
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a, b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

由于`a`和`b`分别是$3\times1$和$1\times2$矩阵，如果让它们相加，它们的形状不匹配。
我们将两个矩阵*广播*为一个更大的$3\times2$矩阵，
如下所示：
- 矩阵`a`将复制列，
- 矩阵`b`将复制行，然后再按元素相加。

In [25]:
a + b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

## 索引和切片

就像在任何其他Python数组中一样，张量中的元素可以通过索引访问。
与任何Python数组一样：第一个元素的索引是0，最后一个元素索引是-1；
可以指定范围以包含第一个元素和最后一个之前的元素。

如下所示，我们[**可以用`[-1]`选择最后一个元素，可以用`[1:3]`选择第二个和第三个元素**]：


# TensorFlow中的`Tensors`是不可变的，也不能被赋值。
# TensorFlow中的`Variables`是支持赋值的可变容器。
# 请记住，TensorFlow中的梯度不会通过`Variable`反向传播。

除了为整个`Variable`分配一个值之外，我们还可以通过索引来写入`Variable`的元素。


## visit elements

In [26]:
X[-1], X[1:3]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>)

In [27]:
X_var = tf.Variable(X)
X_var[1, 2].assign(9)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## 赋值:  Variable.assign( tensor or variable )
如果我们想[**为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。**]
例如，`[0:2, :]`访问第1行和第2行，其中“:”代表沿轴1（列）的所有元素。
虽然我们讨论的是矩阵的索引，但这也适用于向量和超过2个维度的张量。

In [28]:
X_var = tf.Variable(X)
X_var[0:2, :].assign(tf.ones(X_var[0:2,:].shape, dtype = tf.float32) * 12)
X_var.assign(X_var)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## 节省内存

[**运行一些操作可能会导致为新结果分配内存**]。
例如，如果我们用`Y = X + Y`，我们将取消引用`Y`指向的张量，而是指向新分配的内存处的张量。

在下面的例子中，我们用Python的`id()`函数演示了这一点，
它给我们提供了内存中引用对象的确切地址。
运行`Y = Y + X`后，我们会发现`id(Y)`指向另一个位置。
这是因为Python首先计算`Y + X`，为结果分配新的内存，然后使`Y`指向内存中的这个新位置。


In [29]:
before = id(Y)
Y = Y + X
id(Y) == before
# False means the previous Y's memeory are wasted, 
# if we have many parameters, this will be a severe waste

False

这可能是不可取的，原因有两个：首先，我们不想总是不必要地分配内存。
在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。
通常情况下，我们希望原地执行这些更新。
其次，如果我们不原地更新，其他引用仍然会指向旧的内存位置，
这样我们的某些代码可能会无意中引用旧的参数。


`Variables`是TensorFlow中的可变容器，它们提供了一种存储模型参数的方法。
我们可以通过`assign`将一个操作的结果分配给一个`Variable`。
为了说明这一点，我们创建了一个与另一个张量`Y`相同的形状的`Z`，
使用`zeros_like`来分配一个全$0$的块。


In [30]:
Z = tf.Variable(tf.zeros_like(Y))
print('id(Z):', id(Z))
Z.assign(X + Y) # same to Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1519664960320
id(Z): 1519664960320


即使你将状态持久存储在`Variable`中，
你也可能希望避免为不是模型参数的张量过度分配内存，从而进一步减少内存使用量。

由于TensorFlow的`Tensors`是不可变的，而且梯度不会通过`Variable`流动，
因此TensorFlow没有提供一种明确的方式来原地运行单个操作。

但是，TensorFlow提供了`tf.function`修饰符，
将计算封装在TensorFlow图中，该图在运行前经过编译和优化。
这允许TensorFlow删除未使用的值，并复用先前分配的且不再需要的值。
这样可以最大限度地减少TensorFlow计算的内存开销。


In [31]:
@tf.function
def computation(X, Y):
    Z = tf.zeros_like(Y)  # 这个未使用的值将被删除
    A = X + Y  # 当不再需要时，分配将被复用
    B = A + Y
    C = B + Y
    return C + Y

computation(X, Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 8.,  9., 26., 27.],
       [24., 33., 42., 51.],
       [56., 57., 58., 59.]], dtype=float32)>

## tensor and Variable to numpy


将深度学习框架定义的张量[**转换为NumPy张量（`ndarray`）**]很容易，反之也同样容易。
转换后的结果不共享内存。
这个小的不便实际上是非常重要的：当你在CPU或GPU上执行操作的时候，
如果Python的NumPy包也希望使用相同的内存块执行其他操作，你不希望停下计算来等它。


In [32]:
A = X.numpy()
A = X_var.numpy()

B = tf.constant(A)
type(A), type(B)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

## .item() : visit element in tensor

In [33]:
a = tf.constant([3.5]).numpy()
a, a.item(), float(a), int(a)

(array([3.5], dtype=float32), 3.5, 3.5, 3)

# tf.gather() : visit elements according to indices

In [34]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # 这些样本是随机读取的，没有特定的顺序
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        j = tf.constant(indices[i: min(i + batch_size, num_examples)])
        yield tf.gather(features, j), tf.gather(labels, j) # tf.gather(params,indices,axis=0 )