In [1]:
import tensorflow as tf

## Conv2d(卷积核)
tf.keras.layers.Conv2D(  
&nbsp;&nbsp;&nbsp;&nbsp;filters, kernel_size, strides=(1, 1), padding='valid',  
&nbsp;&nbsp;&nbsp;&nbsp;data_format=None, dilation_rate=(1, 1), groups=1, &nbsp;&nbsp;&nbsp;&nbsp;activation=None,  
&nbsp;&nbsp;&nbsp;&nbsp;use_bias=True, kernel_initializer='glorot_uniform',  
&nbsp;&nbsp;&nbsp;&nbsp;bias_initializer='zeros', kernel_regularizer=None,  
&nbsp;&nbsp;&nbsp;&nbsp;bias_regularizer=None, activity_regularizer=None, &nbsp;&nbsp;&nbsp;&nbsp;kernel_constraint=None,  
&nbsp;&nbsp;&nbsp;&nbsp;bias_constraint=None, **kwargs  
)

In [2]:
filters = 1

In [3]:
# 构造一个二维卷积层，它具有1个输出通道和形状为（1，2）的卷积核
conv2d = tf.keras.layers.Conv2D(filters, (1, 2), use_bias=False)

In [4]:
## Padding
## 'same': keep the size the same

In [5]:
# 注意!!! 这里每边都填充了1行或1列，因此总共添加了2行或2列
conv2d = tf.keras.layers.Conv2D(filters, kernel_size=3, padding='same')

In [6]:
conv2d = tf.keras.layers.Conv2D(filters, kernel_size=(5, 3), padding='same')

## stride

In [7]:
conv2d = tf.keras.layers.Conv2D(filters, kernel_size=3, padding='same', strides=2)

In [8]:
conv2d = tf.keras.layers.Conv2D(filters, kernel_size=(3,5), padding='valid',strides=(3, 4))

## Pooling layer(汇聚层)
tf.keras.layers.MaxPool2D(  
&nbsp;&nbsp;&nbsp;&nbsp;pool_size=(2, 2),  
&nbsp;&nbsp;&nbsp;&nbsp;strides=None,  
&nbsp;&nbsp;&nbsp;&nbsp;padding='valid',  
&nbsp;&nbsp;&nbsp;&nbsp;data_format=None,  
)

In [9]:
X = tf.reshape(tf.range(16, dtype=tf.float32), (1, 4, 4, 1))
X

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[12.],
         [13.],
         [14.],
         [15.]]]], dtype=float32)>

### 默认情况下，步幅与汇聚窗口的大小相同。 因此，如果我们使用形状为(3, 3)的汇聚窗口，那么默认情况下，我们得到的步幅形状为(3, 3)。

In [10]:
pool2d = tf.keras.layers.MaxPool2D(pool_size=[3, 3])
pool2d(X)

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[10.]]]], dtype=float32)>

In [11]:
pool2d = tf.keras.layers.MaxPool2D(pool_size=[3, 3], padding='valid',
                                   strides=2)

In [12]:
pool2d = tf.keras.layers.MaxPool2D(pool_size=[2, 3], padding='valid',
                                   strides=(2, 3))